[tool.coverage.run]
branch = true
source = ["zhi_vuepress1_to_vuepress2"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../coverage/packages/zhi-vuepress1-to-vuepress2/html' --cov-report xml:'../../coverage/packages/zhi-vuepress1-to-vuepress2/coverage.xml' --junitxml='../../reports/packages/zhi-vuepress1-to-vuepress2/unittests/junit.xml' --html='../../reports/packages/zhi-vuepress1-to-vuepress2/unittests/html/index.html'"

[tool.poetry]
name = "zhi-vuepress1-to-vuepress2"
version = "1.0.0"
description = "zhi-vuepress1-to-vuepress2"
authors = []
license = 'Proprietary'
readme = 'README.md'

[[tool.poetry.packages]]
include = "zhi_vuepress1_to_vuepress2"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pytest = "^7.2.2"
pydoc-markdown = ">=4.6.4,<5.0"
PyYAML = ">=5.3,<6.0"
pytest-cov = "^4.0.0"
pytest-html = "^3.2.0"
tox = "^4.4.8"
loguru = "^0.6.0"
python-slugify = "^8.0.1"



[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
